### PR TITLE
add foreman vendor

### PR DESCRIPTION
**Pull request by amirfefer**

### CODE REVIEW

**Comment by laviro** [comment]
Thanks for your contribution @amirfefer,
currently we are trying to be compatible with older versions of Foreman.
We'll have a look at this PR after the release for those versions.

**Comment by ShimShtein** [comment]
While we are at it, we should update [foreman core requirement](https://github.com/laviro/inventory_upload/blob/master/lib/foreman_yupana/engine.rb#L24) to the first version that works with vendor.

**Comment by ehelms** [comment]
This would be awesome  to get in for 1.24 as it brings up the compatibility of this plugin and allows us to drop a lot of dependencies in packaging that are only being used by this plugin.

**Comment by adamruzicka** [comment]
Since I don't know if @laviro would be able to rebase this, I took it over in https://github.com/laviro/foreman_inventory_upload/pull/99

**Comment by laviro** [comment]
Thanks guys, back from the holidays :)
Don't worry @ehelms, the version that will support Foreman 1.24 will be using the vendor,
right now we are supporting older Foreman versions first and waiting for some feedback,
later we will create a new branch and add it.

**Comment by ehelms** [comment]
Could you support older versions via a stable branch so that nightly can clean up some nodejs cruft?

**Comment by ShimShtein** [comment]
@ehelms, we will branch once the version is stabilized enough. Right now there a a couple of features in the pipeline (a couple of added fields to the report and switching to per-org report) that should probably make it to the first release.

**Comment by laviro** [comment]
upgrading to the newest versions in #113

**Pull request closed without merging**
